"""Is a published report older than the code that generates it?

Reports in `reports/pipeline/` are machine-generated and machine-cited: the
website pins several of them by path and by 40-character commit SHA, and
`sa mammal check` re-reads the figures out of them. Every one of those
mechanisms compares a report against what the report says. None of them can
notice that the report itself is a fossil.

That gap has already cost a real number. `allosteric_ltr_v1.md` was generated on
2026-05-30. On 2026-06-06, commit 615bb1c fixed `_spearman` to use mid-ranks,
with a commit message naming this very report's tie-heavy baseline column as the
reason. The report was never regenerated. It went on publishing MAMMAL-alone
rho = +0.022 for ten weeks; the correct figure is -0.244, and one of the
per-target correlations feeding the old number was manufactured entirely out of
row order, because all three of that target's scores were bit-identical.

Nothing failed. Every gate passed the whole time, because every gate was reading
the fossil and agreeing with it.

The rule here is deliberately crude: if any file named in a report's
"Generated by" trailer has a commit newer than the report's own last commit, the
report is stale. A subtler rule would have to decide which code changes matter,
and 615bb1c is the proof that this judgement cannot be left to the person making
the change -- they knew, said so in the message, and still did not re-run it.

Crude means false alarms, so staleness is cleared by EVIDENCE, not by exemption.
An attestation in FRESHNESS.json records the exact code SHA a report was checked
against and what happened when it was re-run. When that file changes again the
recorded SHA no longer matches and the report goes back to failing. There is no
way to write "ignore this one" that survives the next commit to its generator.
"""

from __future__ import annotations

import ast
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

# `Generated by `scripts/78_allosteric_ltr.py` via `cluster_a/allosteric_ltr.py`.`
# The `via` half is optional and appears in three spellings: a path relative to
# src/mammal_repurposing, a dotted module, or a bare module name.
_TRAILER = re.compile(
    r"^Generated by\s+`([^`]+)`(?:\s+via\s+`([^`]+)`)?", re.MULTILINE)

_SRC = Path("src") / "mammal_repurposing"

MANIFEST = Path("reports") / "pipeline" / "FRESHNESS.json"

#: `git status -z` separates entries with NUL. Spelled this way so no
#: escape survives a round trip through a shell heredoc as a literal byte.
NUL = chr(0)

#: An attestation may say the report was re-run and matched, or re-run and
#: replaced. It may NOT say the report is fine because someone looked at the
#: diff and formed an opinion -- that is the exact judgement 615bb1c got wrong.
VERIFIED_OUTCOMES = frozenset({"reproduced", "regenerated"})
OUTCOMES = VERIFIED_OUTCOMES | {"unverified"}


@dataclass(frozen=True)
class Staleness:
    report: str
    report_commit: str
    report_date: str
    code: str
    code_commit: str
    code_date: str
    dirty: bool = False

    @property
    def key(self) -> str:
        return f"{self.report}::{self.code}"

    def describe(self) -> str:
        if self.dirty:
            return (f"{self.report} was generated at {self.report_date} "
                    f"({self.report_commit[:7]}); {self.code} is modified in the "
                    f"working tree and uncommitted")
        return (f"{self.report} was generated at {self.report_date} "
                f"({self.report_commit[:7]}); {self.code} changed at "
                f"{self.code_date} ({self.code_commit[:7]}), which is newer")


@dataclass(frozen=True)
class Finding:
    stale: Staleness
    cited: bool
    #: None when nothing in the manifest covers this pair.
    outcome: str | None
    #: Set when an attestation exists but names a code SHA that has since moved.
    superseded_by: str | None = None

    @property
    def cleared(self) -> bool:
        return self.outcome in VERIFIED_OUTCOMES and not self.superseded_by

    @property
    def fails(self) -> bool:
        """Cited reports must be verified. Everything else must at least be
        recorded against the code SHA that outran it, so that the backlog is a
        list someone can work through rather than a silence."""
        if self.cleared:
            return False
        if self.cited:
            return True
        return self.outcome is None or self.superseded_by is not None

    def describe(self) -> str:
        tag = "CITED " if self.cited else ""
        base = f"{tag}{self.stale.describe()}"
        if self.superseded_by:
            return (f"{base}\n      its attestation was against "
                    f"{self.superseded_by[:7]}, which is no longer the newest "
                    f"commit to that file -- re-run and re-record")
        if self.outcome is None:
            return f"{base}\n      no entry in {MANIFEST.as_posix()}"
        if self.outcome == "unverified":
            return f"{base}\n      recorded as unverified backlog"
        return base


def _git(root: Path, *args: str) -> str:
    out = subprocess.run(["git", *args], cwd=root, capture_output=True,
                         text=True, check=False)
    return out.stdout.strip() if out.returncode == 0 else ""


def _last_commit(root: Path, rel: str) -> tuple[str, str, int]:
    """(sha, iso date, unix seconds) of the commit that last touched `rel`."""
    line = _git(root, "log", "-1", "--format=%H%x09%cI%x09%ct", "--", rel)
    if not line or line.count("\t") != 2:
        return ("", "", 0)
    sha, iso, ts = line.split("\t")
    return (sha, iso[:10], int(ts))


def _dirty_set(root: Path) -> set[str]:
    """Every path git reports as changed, in one call. Per-path `git status`
    made this gate take minutes over a corpus this size, which is its own way of
    not being run.

    Parsed with `-z`, so paths carrying spaces or non-ASCII survive and nothing
    depends on line splitting. The first version read `_git(...)`, which strips
    the whole output -- and porcelain's status field is two columns wide, so an
    unstaged modification begins with a space. Stripping ate it, the fixed
    3-character slice then ate a character of the path, and the FIRST changed
    file in any listing quietly stopped counting as dirty. A gate that fails to
    notice its own subject is worse than no gate, so this reads the bytes as
    given.
    """
    out = subprocess.run(["git", "status", "--porcelain", "-z"], cwd=root,
                         capture_output=True, text=True, check=False)
    if out.returncode != 0:
        return set()
    paths: set[str] = set()
    fields = out.stdout.split(NUL)
    i = 0
    while i < len(fields):
        entry = fields[i]
        i += 1
        if len(entry) < 4:
            continue
        status, rel = entry[:2], entry[3:]
        paths.add(rel.replace("\\", "/"))
        if "R" in status or "C" in status:
            # A rename/copy emits its source as the very next NUL field.
            if i < len(fields) and fields[i]:
                paths.add(fields[i].replace("\\", "/"))
            i += 1
    return paths


def split_invocation(script: str) -> tuple[str, list[str]]:
    """`scripts/23_v3_cluster_c.py --skip-txgnn` -> (path, ["--skip-txgnn"]).

    Some trailers record how the script was called, not just which script. That
    is strictly more provenance than a bare path, so it is parsed rather than
    reported as a file that does not exist -- and the flags are then what a
    re-run has to reproduce with.
    """
    parts = script.strip().split()
    return (parts[0], parts[1:]) if parts else (script, [])


def _module_file(root: Path, dotted: str) -> str | None:
    """`mammal_repurposing.validation.retrospective` -> its file, or None."""
    if not dotted.startswith("mammal_repurposing"):
        return None
    tail = dotted[len("mammal_repurposing"):].lstrip(".")
    base = _SRC / "mammal_repurposing" if not tail else _SRC / tail.replace(".", "/")
    for cand in (Path(str(base) + ".py"), base / "__init__.py"):
        if (root / cand).exists():
            return cand.as_posix()
    return None


def _package_of(rel: str) -> str | None:
    """The dotted package a repo-relative source file lives in, for resolving
    relative imports. Files outside src/mammal_repurposing have none."""
    prefix = (_SRC.parent / "mammal_repurposing").as_posix() + "/"
    p = rel if rel.startswith(prefix) else None
    if p is None:
        return None
    inner = p[len(prefix):]
    parts = inner.split("/")[:-1]
    return ".".join(["mammal_repurposing", *parts]) if parts else "mammal_repurposing"


def import_closure(root: Path, start: str, _seen: set[str] | None = None) -> set[str]:
    """Every mammal_repurposing source file `start` reaches through imports.

    A "Generated by" trailer is a hand-written declaration, and a hand-written
    declaration is precisely the thing that fails silently. Three reports in this
    repository were marked fresh by this gate while stale, because their trailers
    named the script and the one module the author had in mind, and the code that
    actually moved was one import further in:

      manuscript_robustness.md declared only its script; its ablation is computed
      by cluster_a/allosteric_ltr.py, which gained a per-fold imputation fix at
      851e3cb after the report was written. Re-running moved the fusion from
      above its no-foundation-model baseline to below it.

      disease_reframe_v1.md declared validation/disease_reframe.py, which does
      `from . import retrospective as R` and calls R.class_loco_g. retrospective
      .py gained a strict leave-one-out fix at eeb27d5 after the report was
      written. Re-running moved the published AUROC from 0.97 [0.91, 1.00] to
      0.95 [0.82, 1.00] -- a number thesupplementadvisor.org was citing.

    So the closure is computed from the AST rather than trusted from prose.
    Imports inside functions count: the scripts here import their modules inside
    main(), which is where both misses above were hiding.

    Unparseable files contribute nothing rather than raising -- a syntax error is
    the test suite's business, not this gate's.
    """
    seen: set[str] = set() if _seen is None else _seen
    if start in seen or not (root / start).exists():
        return seen
    seen.add(start)
    try:
        tree = ast.parse((root / start).read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return seen

    pkg = _package_of(start)
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                found.add(a.name)
        elif isinstance(node, ast.ImportFrom):
            if node.level and pkg:
                # `from . import x` / `from .sub import y`, relative to pkg.
                up = pkg.split(".")
                base = ".".join(up[: len(up) - node.level + 1])
                mod = f"{base}.{node.module}" if node.module else base
            else:
                mod = node.module or ""
            if not mod.startswith("mammal_repurposing"):
                continue
            found.add(mod)
            # `from pkg import name` may import a MODULE named `name`.
            for a in node.names:
                found.add(f"{mod}.{a.name}")

    for dotted in found:
        f = _module_file(root, dotted)
        if f:
            import_closure(root, f, seen)
    return seen


def resolve_code_paths(root: Path, script: str, via: str | None) -> list[str]:
    """Trailer text to repo-relative files. Unresolvable parts are returned
    as-is so the caller can report them rather than skip them.

    This is the DECLARED set only. `scan` adds the transitive import closure on
    top of it; see `import_closure` for why declarations are not enough.
    """
    paths = [split_invocation(script)[0]]
    if via:
        v = via.strip()
        if v.endswith(".py"):
            cand = _SRC / v
        elif "." in v and "/" not in v:
            # `mammal_repurposing.validation.retrospective`
            dotted = v[len("mammal_repurposing."):] if v.startswith(
                "mammal_repurposing.") else v
            cand = _SRC / (dotted.replace(".", "/") + ".py")
        else:
            cand = _SRC / (v + ".py")
        paths.append(cand.as_posix())
    return paths


def trailer_of(path: Path) -> tuple[str, str | None] | None:
    """(script, via) from a report's `Generated by` line, or None."""
    m = _TRAILER.search(path.read_text(encoding="utf-8", errors="replace"))
    return (m.group(1), m.group(2)) if m else None


def generator_args(root: Path, report: str) -> list[str]:
    """The flags a report's trailer records for its own generation."""
    t = trailer_of(root / report)
    return split_invocation(t[0])[1] if t else []


def generator_for(root: Path, report: str) -> str | None:
    """The runnable script named by a report's trailer, stale or not."""
    t = trailer_of(root / report)
    if not t:
        return None
    script = split_invocation(t[0])[0]
    return script if (root / script).exists() else None


class ShallowRepository(RuntimeError):
    """The gate cannot run on a shallow clone, and must not pretend otherwise."""


def assert_deep(root: Path) -> None:
    """Refuse to run where every path resolves to the same commit.

    `actions/checkout` fetches depth 1 by default. Under that, `git log -1 --
    <path>` returns the tip for every file, so no report is ever older than its
    generator and this gate reports a clean corpus on every run without having
    compared anything. That is the exact failure it was written to catch, so it
    is an error rather than a skip: CI must set `fetch-depth: 0`.
    """
    if _git(root, "rev-parse", "--is-shallow-repository") == "true":
        raise ShallowRepository(
            "shallow clone: commit dates are not comparable, so every report "
            "would look fresh. Set `fetch-depth: 0` on actions/checkout.")


def scan(root: Path) -> tuple[list[Staleness], list[str]]:
    """Returns (stale pairs, reports whose trailer names a missing file)."""
    assert_deep(root)
    stale: list[Staleness] = []
    missing: list[str] = []
    dirty = _dirty_set(root)
    seen: dict[str, tuple[str, str, int]] = {}

    def last(rel: str) -> tuple[str, str, int]:
        if rel not in seen:
            seen[rel] = _last_commit(root, rel)
        return seen[rel]

    for rp in sorted((root / "reports" / "pipeline").glob("*.md")):
        text = rp.read_text(encoding="utf-8", errors="replace")
        m = _TRAILER.search(text)
        if not m:
            continue
        rel_report = rp.relative_to(root).as_posix()
        r_sha, r_date, r_ts = last(rel_report)
        if not r_sha:
            # Never committed: no published state to be stale against.
            continue
        declared = resolve_code_paths(root, m.group(1), m.group(2))
        present: list[str] = []
        for code in declared:
            if not (root / code).exists():
                missing.append(f"{rel_report} names `{code}`, which is not a file")
            else:
                present.append(code)
        # The declared set, plus everything it reaches through imports. Three
        # reports were marked fresh while stale because their trailer stopped one
        # import short of the module that moved. See `import_closure`.
        reached: set[str] = set(present)
        for code in present:
            reached |= import_closure(root, code)

        for code in sorted(reached):
            if code in dirty:
                stale.append(Staleness(rel_report, r_sha, r_date, code,
                                       "", "working tree", dirty=True))
                continue
            c_sha, c_date, c_ts = last(code)
            if c_ts > r_ts:
                stale.append(Staleness(rel_report, r_sha, r_date, code,
                                       c_sha, c_date))
    return stale, missing


def load_manifest(root: Path) -> dict:
    p = root / MANIFEST
    if not p.exists():
        return {"cited": [], "attestations": {}}
    data = json.loads(p.read_text(encoding="utf-8"))
    for key, att in data.get("attestations", {}).items():
        if att.get("outcome") not in OUTCOMES:
            raise ValueError(
                f"{MANIFEST.as_posix()}: {key} has outcome "
                f"{att.get('outcome')!r}; expected one of {sorted(OUTCOMES)}")
    return data


def check(root: Path) -> tuple[list[Finding], list[str]]:
    stale, missing = scan(root)
    man = load_manifest(root)
    cited = set(man.get("cited", []))
    atts = man.get("attestations", {})
    findings: list[Finding] = []
    for s in stale:
        att = atts.get(s.key)
        outcome = att.get("outcome") if att else None
        superseded = None
        if att and outcome in VERIFIED_OUTCOMES:
            # The attestation is only as current as the commit it names.
            recorded = att.get("code_commit", "")
            if not s.dirty and recorded != s.code_commit:
                superseded = recorded or "(none recorded)"
            elif s.dirty:
                superseded = recorded or "(none recorded)"
        findings.append(Finding(s, s.report in cited, outcome, superseded))
    return findings, missing
