"""The freshness trailer a generated report carries, and nothing else.

This lives apart from `report_freshness` on purpose. Generators import `stamp` and call it at the
write, which puts whatever module it lives in into every generator's transitive import closure. The
freshness gate computes staleness FROM that closure, so putting `stamp` inside the gate module made
all 31 generated reports stale on every future edit to the gate's own logic. That is noise, it is
permanent, and it would train people to ignore the gate.

This module has exactly one reason to change: the wording of the trailer itself. When it changes,
every report that carries one really is out of date, so the staleness is correct rather than
incidental.
"""
from __future__ import annotations

import re

#: Kept in sync with `report_freshness._TRAILER` by `tests/test_report_freshness.py`. The duplication
#: is deliberate: importing the gate here would put the gate back in every generator's closure and
#: undo the whole point of this module.
_TRAILER_RE = re.compile(r"^Generated by\s+`([^`]+)`(?:\s+via\s+`([^`]+)`)?", re.MULTILINE)


def stamp(text: str, generator: str, via: str | None = None) -> str:
    """Append this report's freshness trailer, unless it already carries one.

    Call it AT THE WRITE, wrapping whatever text the generator produced::

        REPORT.write_text(stamp("\n".join(Ls), "scripts/107_perseus_sensitivity.py"), ...)

    A trailer pasted into a .md by hand survives exactly until the next regeneration, which
    overwrites the file and silently drops it, returning the report to being invisible to the gate.
    That happened twice while the gate was being repaired: once to v8_real_gate1_v1.md during a
    --reproduce, and once to perseus_sensitivity_v1.md on a genuine re-run. Thirty-one reports were
    in that state, and three of them carried hand-added trailers predating any of that work, so the
    trap is older than the repair.

    Emitting from the generator is the only version that survives, because the thing that writes the
    numbers is then also the thing that declares what wrote them.
    """
    if _TRAILER_RE.search(text):
        return text
    tail = f"Generated by `{generator}`" + (f" via `{via}`" if via else "") + "."
    return text.rstrip("\n") + "\n\n" + tail + "\n"
