"""The freshness gate, exercised against real git history in a temp repo.

Mocking git here would test the mock. The whole point of the gate is that it
reads commit order correctly, so every case below builds actual commits.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from mammal_repurposing.provenance.report_freshness import (
    MANIFEST, OUTCOMES, VERIFIED_OUTCOMES, ShallowRepository, assert_deep, check,
    generator_args, generator_for, import_closure, load_manifest,
    resolve_code_paths, scan,
    split_invocation, trailer_of,
)

TRAILER = "Generated by `scripts/gen.py` via `cluster_a/mod.py`."


def _run(repo: Path, *args: str) -> None:
    subprocess.run(args, cwd=repo, check=True, capture_output=True)


def _commit(repo: Path, msg: str, when: str) -> None:
    env = {"GIT_AUTHOR_DATE": when, "GIT_COMMITTER_DATE": when}
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-q", "-m", msg], cwd=repo, check=True,
                   capture_output=True, env={**_env(), **env})


def _env() -> dict:
    import os
    return {**os.environ,
            "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
            "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t"}


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    r = tmp_path / "repo"
    (r / "reports" / "pipeline").mkdir(parents=True)
    (r / "scripts").mkdir()
    (r / "src" / "mammal_repurposing" / "cluster_a").mkdir(parents=True)
    _run(r.parent, "git", "init", "-q", str(r))
    (r / "scripts" / "gen.py").write_text("x = 1\n", encoding="utf-8")
    (r / "src" / "mammal_repurposing" / "cluster_a" / "mod.py").write_text(
        "y = 1\n", encoding="utf-8")
    (r / "reports" / "pipeline" / "a_v1.md").write_text(
        f"# A\n\nrho = +0.5\n\n{TRAILER}\n", encoding="utf-8")
    _commit(r, "seed", "2026-01-01T00:00:00")
    return r


def _touch_code(repo: Path, rel: str, when: str) -> str:
    p = repo / rel
    p.write_text(p.read_text(encoding="utf-8") + "# changed\n", encoding="utf-8")
    _commit(repo, f"touch {rel}", when)
    out = subprocess.run(["git", "log", "-1", "--format=%H", "--", rel],
                         cwd=repo, capture_output=True, text=True, check=True)
    return out.stdout.strip()


# -- the rule itself ---------------------------------------------------------

def test_report_newer_than_its_code_is_fresh(repo: Path) -> None:
    stale, missing = scan(repo)
    assert stale == [] and missing == []


def test_code_committed_after_the_report_is_stale(repo: Path) -> None:
    sha = _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    stale, _ = scan(repo)
    assert [s.code for s in stale] == ["scripts/gen.py"]
    assert stale[0].code_commit == sha
    assert stale[0].report == "reports/pipeline/a_v1.md"


def test_the_via_module_counts_as_generator_code(repo: Path) -> None:
    """The bug that cost +0.022 was in the module, not the script."""
    _touch_code(repo, "src/mammal_repurposing/cluster_a/mod.py",
                "2026-02-01T00:00:00")
    stale, _ = scan(repo)
    assert [s.code for s in stale] == ["src/mammal_repurposing/cluster_a/mod.py"]


def test_regenerating_the_report_clears_it(repo: Path) -> None:
    _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    assert scan(repo)[0]
    p = repo / "reports" / "pipeline" / "a_v1.md"
    p.write_text(f"# A\n\nrho = -0.244\n\n{TRAILER}\n", encoding="utf-8")
    _commit(repo, "regenerate", "2026-03-01T00:00:00")
    assert scan(repo)[0] == []


def test_uncommitted_generator_edit_is_stale(repo: Path) -> None:
    (repo / "scripts" / "gen.py").write_text("x = 2\n", encoding="utf-8")
    stale, _ = scan(repo)
    assert len(stale) == 1 and stale[0].dirty


def test_report_without_a_trailer_is_not_scanned(repo: Path) -> None:
    (repo / "reports" / "pipeline" / "b_v1.md").write_text("# B\n", encoding="utf-8")
    _commit(repo, "add b", "2026-01-02T00:00:00")
    _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    assert {s.report for s in scan(repo)[0]} == {"reports/pipeline/a_v1.md"}


def test_trailer_naming_a_missing_file_is_reported_not_skipped(repo: Path) -> None:
    (repo / "reports" / "pipeline" / "c_v1.md").write_text(
        "# C\n\nGenerated by `scripts/gone.py`.\n", encoding="utf-8")
    _commit(repo, "add c", "2026-01-02T00:00:00")
    _, missing = scan(repo)
    assert len(missing) == 1 and "scripts/gone.py" in missing[0]


# -- attestations ------------------------------------------------------------

def _write_manifest(repo: Path, cited: list[str], atts: dict) -> None:
    (repo / MANIFEST).write_text(
        json.dumps({"cited": cited, "attestations": atts}), encoding="utf-8")


def test_no_attestation_fails(repo: Path) -> None:
    _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    findings, _ = check(repo)
    assert len(findings) == 1 and findings[0].fails
    assert findings[0].outcome is None


def test_reproduced_attestation_clears_it(repo: Path) -> None:
    sha = _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    _write_manifest(repo, [], {
        "reports/pipeline/a_v1.md::scripts/gen.py":
            {"outcome": "reproduced", "code_commit": sha}})
    findings, _ = check(repo)
    assert findings[0].cleared and not findings[0].fails


def test_an_attestation_expires_when_the_code_moves_again(repo: Path) -> None:
    """The property that stops an attestation being a permanent exemption."""
    first = _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    _write_manifest(repo, [], {
        "reports/pipeline/a_v1.md::scripts/gen.py":
            {"outcome": "reproduced", "code_commit": first}})
    assert check(repo)[0][0].cleared

    second = _touch_code(repo, "scripts/gen.py", "2026-03-01T00:00:00")
    assert second != first
    f = check(repo)[0][0]
    assert not f.cleared and f.fails and f.superseded_by == first


def test_unverified_does_not_clear_a_cited_report(repo: Path) -> None:
    sha = _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    _write_manifest(repo, ["reports/pipeline/a_v1.md"], {
        "reports/pipeline/a_v1.md::scripts/gen.py":
            {"outcome": "unverified", "code_commit": sha}})
    f = check(repo)[0][0]
    assert f.cited and f.fails and not f.cleared


def test_unverified_holds_a_non_cited_report_as_backlog(repo: Path) -> None:
    sha = _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    _write_manifest(repo, [], {
        "reports/pipeline/a_v1.md::scripts/gen.py":
            {"outcome": "unverified", "code_commit": sha}})
    f = check(repo)[0][0]
    assert not f.fails and not f.cleared


def test_a_bogus_outcome_is_rejected_rather_than_ignored(repo: Path) -> None:
    _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    _write_manifest(repo, [], {
        "reports/pipeline/a_v1.md::scripts/gen.py":
            {"outcome": "looks fine to me", "code_commit": "x"}})
    with pytest.raises(ValueError, match="looks fine to me"):
        load_manifest(repo)


def test_verified_outcomes_are_the_two_that_require_a_re_run() -> None:
    assert VERIFIED_OUTCOMES == {"reproduced", "regenerated"}
    assert OUTCOMES - VERIFIED_OUTCOMES == {"unverified"}


# -- trailer parsing ---------------------------------------------------------

@pytest.mark.parametrize("via,expected", [
    ("cluster_a/mod.py", "src/mammal_repurposing/cluster_a/mod.py"),
    ("mammal_repurposing.validation.retrospective",
     "src/mammal_repurposing/validation/retrospective.py"),
    ("validation.retrospective", "src/mammal_repurposing/validation/retrospective.py"),
])
def test_via_spellings_all_resolve(repo: Path, via: str, expected: str) -> None:
    assert resolve_code_paths(repo, "scripts/gen.py", via)[1] == expected


def test_a_trailer_may_record_its_invocation(repo: Path) -> None:
    assert split_invocation("scripts/x.py --skip-txgnn") == ("scripts/x.py",
                                                             ["--skip-txgnn"])
    (repo / "reports" / "pipeline" / "d_v1.md").write_text(
        "# D\n\nGenerated by `scripts/gen.py --fast`.\n", encoding="utf-8")
    _commit(repo, "add d", "2026-01-02T00:00:00")
    assert generator_for(repo, "reports/pipeline/d_v1.md") == "scripts/gen.py"
    assert generator_args(repo, "reports/pipeline/d_v1.md") == ["--fast"]
    assert scan(repo)[1] == []


def test_trailer_of_returns_none_without_one(repo: Path) -> None:
    (repo / "reports" / "pipeline" / "e_v1.md").write_text("# E\n", encoding="utf-8")
    assert trailer_of(repo / "reports" / "pipeline" / "e_v1.md") is None


# -- the environment the gate refuses to run in ------------------------------

def test_a_shallow_clone_is_refused_not_silently_passed(repo: Path,
                                                        tmp_path: Path) -> None:
    """At depth 1 every path resolves to the same commit, so nothing looks
    stale. Passing there would be the gate's own failure mode."""
    _touch_code(repo, "scripts/gen.py", "2026-02-01T00:00:00")
    assert scan(repo)[0], "sanity: deep clone sees the staleness"

    shallow = tmp_path / "shallow"
    subprocess.run(["git", "clone", "-q", "--depth", "1",
                    repo.as_uri(), str(shallow)], check=True, capture_output=True)
    assert (shallow / ".git" / "shallow").exists()
    with pytest.raises(ShallowRepository, match="fetch-depth"):
        scan(shallow)


def test_a_full_clone_passes_the_depth_check(repo: Path) -> None:
    assert_deep(repo)


# -- the import closure ------------------------------------------------------
#
# Every case here is a shape that was marked FRESH while stale in the real
# repository, because a "Generated by" trailer is a hand-written declaration and
# the code that moved was one import further in.

TRAILER_SCRIPT_ONLY = "Generated by `scripts/gen.py`."


def _script_only_report(repo: Path, body: str) -> None:
    (repo / "reports" / "pipeline" / "s_v1.md").write_text(
        f"# S\n\nrho = +0.5\n\n{TRAILER_SCRIPT_ONLY}\n", encoding="utf-8")
    (repo / "scripts" / "gen.py").write_text(body, encoding="utf-8")


def test_a_module_the_script_imports_counts_even_when_undeclared(repo: Path) -> None:
    """manuscript_robustness.md: trailer named only the script; the ablation was
    computed by a module it imports, which had since gained a leakage fix."""
    _script_only_report(repo, "from mammal_repurposing.cluster_a import mod\n")
    _commit(repo, "script-only trailer", "2026-01-02T00:00:00")
    # Scoped to this report: rewriting gen.py in a later commit legitimately
    # makes the fixture's OTHER report stale, which is the gate working.
    assert [s for s in scan(repo)[0] if s.report == "reports/pipeline/s_v1.md"] == []

    _touch_code(repo, "src/mammal_repurposing/cluster_a/mod.py",
                "2026-02-01T00:00:00")
    stale = [s for s in scan(repo)[0] if s.report == "reports/pipeline/s_v1.md"]
    assert [s.code for s in stale] == ["src/mammal_repurposing/cluster_a/mod.py"]


def test_the_closure_is_transitive(repo: Path) -> None:
    """disease_reframe.py declared, but it does `from . import retrospective`
    and calls into it. The gate has to follow the second hop."""
    deep = repo / "src" / "mammal_repurposing" / "cluster_a" / "deep.py"
    deep.write_text("Z = 1\n", encoding="utf-8")
    (repo / "src" / "mammal_repurposing" / "cluster_a" / "mod.py").write_text(
        "from mammal_repurposing.cluster_a import deep\ny = 1\n", encoding="utf-8")
    _script_only_report(repo, "from mammal_repurposing.cluster_a import mod\n")
    _commit(repo, "two hops", "2026-01-02T00:00:00")

    _touch_code(repo, "src/mammal_repurposing/cluster_a/deep.py",
                "2026-02-01T00:00:00")
    stale = [s for s in scan(repo)[0] if s.report == "reports/pipeline/s_v1.md"]
    assert [s.code for s in stale] == ["src/mammal_repurposing/cluster_a/deep.py"]


def test_relative_imports_resolve(repo: Path) -> None:
    """`from . import retrospective as R` is the exact spelling that hid the
    AUROC the website was publishing."""
    sib = repo / "src" / "mammal_repurposing" / "cluster_a" / "sib.py"
    sib.write_text("W = 1\n", encoding="utf-8")
    (repo / "src" / "mammal_repurposing" / "cluster_a" / "mod.py").write_text(
        "from . import sib as S\ny = 1\n", encoding="utf-8")
    _script_only_report(repo, "from mammal_repurposing.cluster_a import mod\n")
    _commit(repo, "relative import", "2026-01-02T00:00:00")

    _touch_code(repo, "src/mammal_repurposing/cluster_a/sib.py",
                "2026-02-01T00:00:00")
    stale = [s for s in scan(repo)[0] if s.report == "reports/pipeline/s_v1.md"]
    assert [s.code for s in stale] == ["src/mammal_repurposing/cluster_a/sib.py"]


def test_imports_inside_a_function_count(repo: Path) -> None:
    """The scripts here import their modules inside main(), which is where both
    real misses were hiding. A module-level-only walk would not have seen them."""
    _script_only_report(
        repo,
        "def main():\n"
        "    from mammal_repurposing.cluster_a import mod\n"
        "    return mod\n")
    _commit(repo, "function-local import", "2026-01-02T00:00:00")

    _touch_code(repo, "src/mammal_repurposing/cluster_a/mod.py",
                "2026-02-01T00:00:00")
    stale = [s for s in scan(repo)[0] if s.report == "reports/pipeline/s_v1.md"]
    assert [s.code for s in stale] == ["src/mammal_repurposing/cluster_a/mod.py"]


def test_third_party_imports_are_not_followed(repo: Path) -> None:
    _script_only_report(repo, "import numpy as np\nimport pandas\n")
    _commit(repo, "third party", "2026-01-02T00:00:00")
    assert import_closure(repo, "scripts/gen.py") == {"scripts/gen.py"}


def test_a_syntax_error_does_not_break_the_gate(repo: Path) -> None:
    """A broken file is the test suite's problem. This gate degrades to the
    declared set rather than raising and taking CI down with it."""
    _script_only_report(repo, "def main(:\n    pass\n")
    _commit(repo, "unparseable", "2026-01-02T00:00:00")
    assert import_closure(repo, "scripts/gen.py") == {"scripts/gen.py"}


def test_an_import_cycle_terminates(repo: Path) -> None:
    a = repo / "src" / "mammal_repurposing" / "cluster_a" / "mod.py"
    b = repo / "src" / "mammal_repurposing" / "cluster_a" / "other.py"
    a.write_text("from . import other\n", encoding="utf-8")
    b.write_text("from . import mod\n", encoding="utf-8")
    _script_only_report(repo, "from mammal_repurposing.cluster_a import mod\n")
    _commit(repo, "cycle", "2026-01-02T00:00:00")
    got = import_closure(repo, "scripts/gen.py")
    assert "src/mammal_repurposing/cluster_a/other.py" in got
    assert "src/mammal_repurposing/cluster_a/mod.py" in got


def test_every_published_report_declares_itself(tmp_path):
    """2026-09-20. Omission was the cheapest exemption in the repository.

    `scan` skips any report with no `Generated by` trailer, so a report that simply never declared
    one was invisible: no attestation, no named code, and it survived every future commit to its
    generator. 31 of 115 reports were in that state, including `l4_window_precision_v1.md` (whose
    generator `engine/psychoplastogen.py` changed the same week) and a WEBSITE-CITED report,
    `v8_real_gate1_v1.md`, stale against both its script and `cluster_e/gate1.py`. The gate printed
    "failing 0" throughout. Declaring them surfaced 61 failing pairs across 21 reports.

    This test is the durable half of the fix. Trailers were added to the generators, but a future
    generator that forgets one, or a regeneration that drops one, would silently restore the hole.
    This fails the moment that happens.
    """
    from mammal_repurposing.provenance.report_freshness import undeclared_reports
    root = Path(__file__).resolve().parents[1]
    undeclared = undeclared_reports(root)
    assert undeclared == [], (
        "these reports declare neither a generator nor that they have none, so the freshness gate "
        "cannot see them at all:\n  " + "\n  ".join(undeclared)
        + "\n\nAdd a `Generated by `script`.` trailer (emitted BY the generator, not pasted into "
          "the .md), or state `Written by hand; this report has no generator.`")


def test_a_trailer_commit_does_not_certify_a_stale_report():
    """2026-09-20. I broke the gate with a one-line edit, and this is the guard.

    The gate dates a report by the last commit that TOUCHED it, so ANY edit resets "generated at".
    Committing a one-line `Generated by` trailer onto 21 stale reports marked all 21 fresh without
    a single generator being re-run, six of them PERSEUS reports whose substance the L4 demotion
    reverses. The hole predates the trailer work: a typo fix or a reflowed paragraph would have
    done the same thing, silently.

    Freshness is now dated from the last SUBSTANTIVE commit. These assertions pin the classifier
    that decides which commits count.
    """
    from mammal_repurposing.provenance.report_freshness import _declaration_only

    trailer_only = (
        "diff --git a/reports/pipeline/x.md b/reports/pipeline/x.md\n"
        "@@ -50,0 +51,2 @@\n"
        "+\n"
        "+Generated by `scripts/107_perseus_sensitivity.py`.\n")
    assert _declaration_only(trailer_only), "a trailer-only commit must not re-date a report"

    narrative_only = (
        "@@ -10,0 +11,2 @@\n"
        "+\n"
        "+Written by hand; this report has no generator.\n")
    assert _declaration_only(narrative_only)

    # a real regeneration changes numbers, and MUST re-date the report
    substantive = (
        "@@ -20,2 +20,2 @@\n"
        "-| MAMMAL pKd only | +0.022 |\n"
        "+| MAMMAL pKd only | -0.244 |\n")
    assert not _declaration_only(substantive), "a changed figure must count as a regeneration"

    # a mixed commit counts as substantive: the declaration must not launder the rest
    mixed = trailer_only + substantive
    assert not _declaration_only(mixed), (
        "adding a trailer alongside a real edit must not make the real edit invisible")


def test_the_trailer_module_stays_in_sync_with_the_gate():
    """`trailer.stamp` deliberately duplicates the gate's trailer regex. This keeps them honest.

    Generators call `stamp` at the write, which puts its module into every generator's transitive
    import closure, and the gate computes staleness FROM that closure. Keeping `stamp` inside
    `report_freshness` therefore made all 31 generated reports stale on every edit to the gate's own
    logic, which is permanent noise that would train people to ignore the gate. So `stamp` lives in
    `provenance.trailer`, which has exactly one reason to change.

    The cost is a duplicated pattern. This test is the price of that, and it is cheap.
    """
    from mammal_repurposing.provenance.report_freshness import _TRAILER
    from mammal_repurposing.provenance.trailer import _TRAILER_RE, stamp

    assert _TRAILER.pattern == _TRAILER_RE.pattern, (
        "provenance.trailer._TRAILER_RE has drifted from report_freshness._TRAILER. A report "
        "stamped by one and read by the other would go invisible to the gate.")

    # what stamp writes must be what the gate reads
    out = stamp("# R\nbody", "scripts/x.py")
    m = _TRAILER.search(out)
    assert m and m.group(1) == "scripts/x.py"
    out2 = stamp("# R\nbody", "scripts/x.py", "cluster_a/y.py")
    m2 = _TRAILER.search(out2)
    assert m2 and m2.group(1) == "scripts/x.py" and m2.group(2) == "cluster_a/y.py"
    assert stamp(out, "scripts/other.py") == out, "stamp must be idempotent"
