"""Train + scaffold-evaluate the PERSEUS L1 Stage-3 efflux-aware conformal logBB regressor.

LightGBM on RDKit descriptors + the Didziapetris P-gp efflux feature, with a Bemis-Murcko
scaffold split (no analog leakage), Mondrian split-conformal calibration, and a kNN
applicability-domain threshold. Reports R2/RMSE/MAE HONESTLY against the field ceiling
(public CNS-penetration models plateau modestly), plus the empirical conformal coverage.

Saves data/interim/free_exposure_model.joblib (gitignored; regenerated by this script).
Writes reports/pipeline/cns_exposure_kpuu_v1.md. CPU.
"""
from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

from mammal_repurposing.engine.free_exposure import (
    FEATURE_NAMES, FreeExposureModel, PENETRATION_LOGBB, featurize, free_exposure_gate,
    mondrian_quantiles, scaffold_split,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
L = logging.getLogger("train_logbb")

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "raw" / "logbb_b3db.csv"
MODEL_OUT = ROOT / "data" / "interim" / "free_exposure_model.joblib"
REPORT = ROOT / "reports" / "pipeline" / "cns_exposure_kpuu_v1.md"
ALPHA = 0.1   # 90% prediction interval


def main() -> int:
    df = pd.read_csv(DATA)
    feats, cats, ys, smis = [], [], [], []
    for _, r in df.iterrows():
        f = featurize(r["smiles"])
        if f is None:
            continue
        feats.append(f[0]); cats.append(f[1]); ys.append(float(r["logbb"])); smis.append(r["smiles"])
    X = np.vstack(feats); y = np.asarray(ys); cats = np.asarray(cats)
    L.info("Featurized %d/%d compounds; P-gp cats %s", len(X), len(df),
           {c: int((cats == c).sum()) for c in set(cats)})

    tr, ca, te = scaffold_split(smis, fracs=(0.7, 0.15, 0.15))
    L.info("Scaffold split: train %d / cal %d / test %d", len(tr), len(ca), len(te))

    import lightgbm as lgb
    model = lgb.LGBMRegressor(n_estimators=400, learning_rate=0.05, num_leaves=31,
                              min_child_samples=20, subsample=0.8, colsample_bytree=0.8,
                              random_state=0, verbose=-1)
    model.fit(X[tr], y[tr])

    # honest held-out metrics (scaffold test split)
    yhat_te = model.predict(X[te])
    ss_res = float(((y[te] - yhat_te) ** 2).sum())
    ss_tot = float(((y[te] - y[te].mean()) ** 2).sum())
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else float("nan")
    rmse = float(np.sqrt(((y[te] - yhat_te) ** 2).mean()))
    mae = float(np.abs(y[te] - yhat_te).mean())

    # Mondrian split-conformal on the calibration split
    res_ca = np.abs(y[ca] - model.predict(X[ca]))
    conformal = mondrian_quantiles(res_ca, list(cats[ca]), alpha=ALPHA)

    # applicability-domain threshold: 99th pct of train kNN distance (standardized)
    mean, std = X[tr].mean(axis=0), X[tr].std(axis=0) + 1e-9
    tr_scaled = (X[tr] - mean) / std
    k = 5
    dists = []
    for i in range(len(tr_scaled)):
        d = np.sqrt(((tr_scaled - tr_scaled[i]) ** 2).sum(axis=1))
        dists.append(np.partition(d, k)[1:k + 1].mean())   # exclude self
    ad_threshold = float(np.percentile(dists, 99))

    fem = FreeExposureModel(model=model, scaler_mean=mean, scaler_std=std, train_scaled=tr_scaled,
                            conformal=conformal, ad_threshold=ad_threshold, ad_k=k, alpha=ALPHA,
                            metrics={"r2": r2, "rmse": rmse, "mae": mae, "n_test": len(te)})

    # empirical conformal coverage on the test split (target ~90%)
    cov = 0
    for i in te:
        p = fem.predict(smis[i])
        if p is not None and p.lo <= y[i] <= p.hi:
            cov += 1
    coverage = cov / len(te)

    MODEL_OUT.parent.mkdir(parents=True, exist_ok=True)
    fem.save(MODEL_OUT)
    L.info("Saved %s", MODEL_OUT)
    L.info("Scaffold-test: R2 %.2f RMSE %.2f MAE %.2f | conformal coverage %.2f (target %.2f)",
           r2, rmse, mae, coverage, 1 - ALPHA)

    write_report(fem, coverage, conformal, ad_threshold, cats)
    return 0


def write_report(fem, coverage, conformal, ad_threshold, cats) -> None:
    m = fem.metrics
    Ls = ["# PERSEUS L1 Stage-3 - efflux-aware conformal logBB regressor", "",
          "Replaces the Stage-3 ABSTAIN stub with a quantitative, uncertainty-banded CNS-"
          "penetration call. Reproduced by `scripts/110_fetch_logbb.py` + "
          "`scripts/111_train_logbb.py`.", "",
          "**HONEST SCOPE:** the trained target is **logBB** (log10 total brain:plasma, B3DB "
          "CC0), a passive-penetration proxy - NOT the unbound Kp,uu that finally governs free "
          "target exposure (Kp,uu is efflux-dominated; its public data are tiny/license-"
          "encumbered). Stage-3 is therefore an efflux-AWARE logBB predictor with a calibrated "
          "abstain-wide band; true Kp,uu remains the documented residual gap.", "",
          "## Held-out performance (Bemis-Murcko scaffold split, no analog leakage)", "",
          f"- R2 **{m['r2']:.2f}**, RMSE **{m['rmse']:.2f}**, MAE **{m['mae']:.2f}** "
          f"(n_test={m['n_test']}).",
          "- Honest context: public CNS free-exposure/penetration models plateau at modest "
          "accuracy (rat Kp,uu R2 ~0.3-0.6; Friden 0.45, AZ 0.53, Takeda 0.60/0.48). The "
          "deliverable is the CALIBRATED INTERVAL + abstain rule, not a high R2.", "",
          f"## Conformal calibration (Mondrian by P-gp category, {int((1-fem.alpha)*100)}% PI)", "",
          f"- Empirical coverage on the scaffold-test split: **{coverage:.2f}** "
          f"(target {1-fem.alpha:.2f}).",
          "- Per-category half-width (absolute-residual quantile):"]
    for c in ("substrate", "uncertain", "nonsubstrate", "_pooled"):
        if c in conformal and conformal[c] == conformal[c]:
            Ls.append(f"  - {c}: +/-{conformal[c]:.2f} logBB")
    Ls += ["", f"- Applicability-domain kNN(5) distance threshold (99th pct of train): "
           f"{ad_threshold:.2f}; queries beyond it ABSTAIN.", "",
           "## Efflux feature (the model-within-a-model lever)", "",
           "P-gp-substrate likelihood (Didziapetris 2003: high N+O count + MW favour efflux) is "
           "an explicit input AND the Mondrian conformal category. Training-set P-gp mix: "
           + ", ".join(f"{c} {int((np.asarray(cats)==c).sum())}" for c in ("substrate", "uncertain", "nonsubstrate")) + ".", "",
           "## Stage-3 gate", "",
           f"PASS if the conformal logBB lower bound >= {PENETRATION_LOGBB} (CNS+ cutoff, Clark "
           "2003); FAIL if the upper bound < threshold OR a predicted P-gp substrate has point "
           "logBB < threshold (efflux likely kills free exposure); ABSTAIN if out of the "
           "conformal applicability domain or the band straddles the threshold. Wired into "
           "`engine/cns_exposure.py` as an efflux-aware refinement of the passive-penetration "
           "verdict.", ""]
    REPORT.write_text("\n".join(Ls), encoding="utf-8")
    L.info("Wrote %s", REPORT)


if __name__ == "__main__":
    raise SystemExit(main())
