"""§8.6 — Annotate v7 wet-lab shortlist with brain-region bias.

Adds three columns to the v7 ranking:
  brain_bias            — cortex-biased | subcortical | brainstem | hippocampal | mixed
  brain_primary_region  — text description of the dominant expression region
  brain_note            — short literature pointer

Output: data/results/v2/brain_region_v1.parquet + reports/brain_region_v1.md.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from mammal_repurposing.analysis.brain_region import (  # noqa: E402
    annotate, summary_counts, BRAIN_REGION_BIAS,
)

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("v5_brain_region")

DEFAULT_RANKING = ROOT / "data" / "results" / "v2" / "final_ranking_v7_moa.parquet"
DEFAULT_OUT = ROOT / "data" / "results" / "v2" / "brain_region_v1.parquet"
DEFAULT_REPORT = ROOT / "reports" / "brain_region_v1.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ranking", type=Path, default=DEFAULT_RANKING)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--top-n", type=int, default=30)
    args = parser.parse_args()

    rk = pd.read_parquet(args.ranking)
    annotated = annotate(rk, target_col="mammal_best_target")
    annotated.to_parquet(args.out, index=False)
    logger.info("Wrote %s", args.out)

    counts = summary_counts()

    L: list[str] = []
    L.append("# Brain-Region Selectivity v1 (§8.6 preview)")
    L.append("")
    L.append("Hand-curated mapping of each 22-target cognition panel member "
             "to a coarse anatomical bias category, synthesised from AHBA "
             "(Hawrylycz 2012), GTEx, and Siletti 2023 single-cell atlas. "
             "**This is the V6 Cluster D entry point** — the full Bayesian "
             "AHBA+OT-Genetics+cellxgene model is documented at "
             "`research/4-tier/Multi-Source Neurobiological Prior...md` "
             "(~16 weeks).")
    L.append("")
    L.append("## Per-target panel bias distribution (22 targets)")
    L.append("")
    L.append("| Bias category | N targets |")
    L.append("|---|---|")
    for cat, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        L.append(f"| {cat} | {n} |")
    L.append("")

    L.append("## Panel map")
    L.append("")
    L.append("| UniProt | Gene | Bias | Primary region | Note |")
    L.append("|---|---|---|---|---|")
    for u, e in sorted(BRAIN_REGION_BIAS.items(),
                       key=lambda x: (x[1]["bias"], x[1]["gene"])):
        L.append(f"| {u} | {e['gene']} | {e['bias']} | {e['primary_region']} | {e['note']} |")
    L.append("")

    L.append(f"## Top-{args.top_n} v7 ranking with brain-region annotation")
    L.append("")
    L.append("| # | Compound | Tier | RRF | MAMMAL best | Brain bias | Primary region |")
    L.append("|---|---|---|---|---|---|---|")
    for i, r in annotated.head(args.top_n).iterrows():
        L.append(f"| {i+1} | {r['compound_name']} | "
                 f"{r.get('evidence_tier','?')} | {r['rrf_score']:.3f} | "
                 f"{r.get('mammal_best_target','')} | "
                 f"{r['brain_bias']} | {r['brain_primary_region'][:60]} |")
    L.append("")

    L.append("## Hypothesis test")
    L.append("")
    L.append("**Claim**: the V5 wet-lab top-25 spans ≥3 distinct brain-region "
             "bias categories. This is a sanity check that the pipeline isn't "
             "lopsided toward a single anatomy.")
    top25 = annotated.head(25)
    distinct = sorted(set(top25["brain_bias"]) - {""})
    n_distinct = len(distinct)
    verdict = "PASS" if n_distinct >= 3 else "DEGRADE"
    L.append("")
    L.append(f"**Measured**: {n_distinct} distinct bias categories in top-25: "
             f"{sorted(distinct)}")
    L.append(f"**Verdict**: {verdict}")
    L.append("")
    L.append("---")
    L.append("")
    L.append("Generated by `scripts/45_v5_brain_region.py`. Full V6 Cluster D "
             "Bayesian pipeline pending.")
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text("\n".join(L), encoding="utf-8")
    logger.info("Wrote %s. Brain-region diversity test: %s (n=%d in top-25)",
                args.report, verdict, n_distinct)
    return 0 if verdict == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
