"""Gap 7 — Generate the prospective mechanism-justified repurposing shortlist.

For each disease (AD / CIAS / FXS), ranks named/approved drugs by
disease-class-prognostic-prior × target engagement (success-track-record
classes only), flags NOVEL repurposing hypotheses vs known uses, and emits GRADE
dossiers for the top novel picks.

Output: reports/repurposing_shortlist_v1.md

Usage:
  python scripts/82_repurposing_shortlist.py
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("repurposing")

DISEASES = ["AD", "CIAS", "FXS"]


def render(report: Path, per_disease: dict, dossiers: dict) -> None:
    L: list[str] = []
    L.append("# Prospective Repurposing Shortlist (Gap 7 — capstone)")
    L.append("")
    L.append("The deliverable the pipeline was built for: **approved drugs as "
             "mechanism-justified repurposing hypotheses** for cognitive-impairment "
             "diseases. Each candidate is ranked by the one signal the project proved "
             "is prognostic — its mechanism class's pivotal-trial track record in that "
             "disease (Gap 3 / Gap 6) — times how well it engages a disease-relevant "
             "target. Restricted to **SUCCESS-track-record mechanism classes**.")
    L.append("")
    L.append("> These are hypotheses worth evaluation, **not** predicted cures. Effect "
             "sizes remain bounded by the Roberts 2020 ceiling; engagement flagged "
             "*uncertain* is at an allosteric/transporter target where MAMMAL's "
             "sequence-only binding is unreliable (Gap 4). Novelty is flagged against "
             "a curated indication map — a **NOVEL** row is an approved drug whose "
             "mechanism class succeeds in this disease but which is not currently used "
             "for it.")
    L.append("")

    for disease, cands in per_disease.items():
        L.append("---")
        L.append("")
        L.append(f"## {disease}")
        L.append("")
        novel = [c for c in cands if c.novel]
        L.append(f"{len(cands)} drugs in SUCCESS-track-record classes engage a "
                 f"{disease}-relevant target; **{len(novel)} are NOVEL repurposing "
                 f"hypotheses** (approved elsewhere, not used for {disease}).")
        L.append("")
        L.append("| Rank | Drug | Currently used for | Mechanism class | Target | Class g | Engagement | NOVEL? |")
        L.append("|---|---|---|---|---|---|---|---|")
        for i, c in enumerate(cands[:12], 1):
            eng = f"{c.engagement:.0%}{'' if c.engagement_reliable else ' ⚠'}"
            nov = "🔵 **NOVEL**" if c.novel else "standard"
            L.append(f"| {i} | {c.compound} | {c.current_use} | {c.mechanism_class} | "
                     f"{c.target_gene} | {c.class_g:+.2f} | {eng} | {nov} |")
        L.append("")
        if novel:
            L.append(f"### Top NOVEL {disease} repurposing hypotheses")
            L.append("")
            for c in novel[:4]:
                L.append(f"- **{c.compound}** ({c.mechanism_class}, currently "
                         f"{c.current_use}): {c.rationale}")
                if c.liabilities:
                    L.append(f"  - liability flags: {', '.join(c.liabilities)}")
            L.append("")

    # dossiers for the top novel picks across diseases
    if dossiers:
        L.append("---")
        L.append("")
        L.append("## Evidence dossiers — top novel repurposing picks")
        L.append("")
        for md in dossiers.values():
            L.append(md)
            L.append("---")
            L.append("")

    L.append("Generated by `scripts/82_repurposing_shortlist.py` via "
             "`reporting/repurposing_shortlist.py` (integrates Gap 2 disease priors + "
             "Gap 4 engagement-reliability + Gap 5 dossiers).")
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(L), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--compounds", type=Path,
                    default=ROOT / "data" / "interim" / "compounds.parquet")
    ap.add_argument("--grid", type=Path,
                    default=ROOT / "data" / "results" / "v2" / "v6a_grid_expanded.parquet")
    ap.add_argument("--ledger", type=Path,
                    default=ROOT / "data" / "raw" / "clinical_outcomes_ledger.csv")
    ap.add_argument("--anchors", type=Path,
                    default=ROOT / "data" / "raw" / "modulator_anchors_seed.csv")
    ap.add_argument("--liability", type=Path,
                    default=ROOT / "data" / "results" / "liability_dti.parquet")
    ap.add_argument("--panel", type=Path,
                    default=ROOT / "data" / "interim" / "targets.parquet")
    ap.add_argument("--report", type=Path,
                    default=ROOT / "reports" / "repurposing_shortlist_v1.md")
    args = ap.parse_args()

    from mammal_repurposing.validation import retrospective as R
    from mammal_repurposing.validation import disease_reframe as D
    from mammal_repurposing.reporting import repurposing_shortlist as RS
    from mammal_repurposing.reporting import clinician_dossier as Dx

    comp = pd.read_parquet(args.compounds)
    named = comp[comp["evidence_tier"].isin(
        ["positive_control", "named_in_research", "extended_cns"])].copy()
    named = named[named["expected_top_target"].notna()]
    # add the curated approved-drug supplement at the new panel targets (M1/M4,
    # 5-HT1A, PDE4, 5-HT4, GlyT1, 5-HT6) so the muscarinic/serotonergic
    # repurposing hypotheses the panel expansion enabled can surface
    from mammal_repurposing.reporting.repurposing_shortlist import named_drugs_with_supplement
    named = named_drugs_with_supplement(named)

    grid = pd.read_parquet(args.grid)
    ledger = R.load_clinical_ledger(args.ledger)
    anchors = pd.read_csv(args.anchors, comment="#")
    liability = pd.read_parquet(args.liability) if args.liability.exists() else None
    panel = pd.read_parquet(args.panel)
    panel_u = set(panel["uniprot"].astype(str))
    gene = dict(zip(panel["uniprot"].astype(str), panel["gene"]))
    for _, r in ledger.iterrows():
        gene.setdefault(str(r["target_uniprot"]), str(r["target_uniprot"]))

    evidence = D.load_disease_evidence(ledger, anchors)
    tcmap = D.disease_target_class_map()

    per_disease, dossiers = {}, {}
    for disease in DISEASES:
        priors = D.build_disease_class_priors(disease, evidence)
        cands = RS.build_repurposing_shortlist(
            disease, named, priors, grid, tcmap,
            liability_df=liability, panel_uniprots=panel_u)
        per_disease[disease] = cands
        # dossier for the single top NOVEL pick per disease
        novel = [c for c in cands if c.novel]
        if novel:
            c = novel[0]
            lrow = None
            lm = ledger[(ledger["compound"].str.lower() == c.compound.lower())]
            if len(lm):
                lrow = lm.iloc[0]
            card = Dx.build_dossier(
                c.compound, disease, ledger=ledger, disease_priors=priors,
                ledger_row=lrow, liability_df=liability, panel_uniprots=panel_u,
                binding_reliable=c.engagement_reliable,
                target_gene=c.target_gene, mechanism_class=c.mechanism_class)
            dossiers[f"{disease}:{c.compound}"] = Dx.render_card_md(card)

    render(args.report, per_disease, dossiers)

    logger.info("=" * 66)
    for disease, cands in per_disease.items():
        novel = [c for c in cands if c.novel]
        logger.info("[%s] %d success-class candidates, %d NOVEL. Top novel: %s",
                    disease, len(cands), len(novel),
                    ", ".join(f"{c.compound}({c.mechanism_class})" for c in novel[:3]))
    logger.info("Wrote %s", args.report)
    logger.info("=" * 66)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
